variables:
  DEPLOY_PATH: D:\deploy\mynews\

stages:
  - build
  - deploy

build:
  stage: build
  only:
    - master
  before_script:
    - whoami
  script:
    - echo "build job"
    - npm run build:mp-weixin
  tags:
    - WP_WEIXIN
  artifacts:
    paths:
      - dist/build/mp-weixin
    expire_in: 3 days

deploy:
  stage: deploy
  only:
    - master
  tags: 
    - WP_WEIXIN
  before_script:
    - whoami
  script:
    - echo "deploy job"
    - xcopy .\dist\build\mp-weixin $DEPLOY_PATH /s/y
