variables:
  WEIXIN_DEPLOY_PATH: D:\deploy\weixin\mynews\
  DINGDING_DEPLOY_PATH: D:\deploy\dingding\mynews\

stages:
  - prepare
  - test
#  - analysis
  - build
  - deploy

prepare:
  stage: prepare
  cache:
    key: mynews_demo_node_modules
    paths:
      - node_modules
      - app/node_modules
  script:
    - pwd
    - npm install --registry https://registry.npm.taobao.org
    - cd app & npm install
  only:
    - kelvin
  tags:
    - MY_NEW

test:
  stage: test
  cache:
    key: mynews_demo_node_modules
    policy: pull
    paths:
      - app/node_modules
  script:
    - pwd
    - cd app & npm run test
  only:
    - master
    - kelvin
  tags:
    - MY_NEW

#sonar_preview:
#  stage: analysis
#  dependencies:
#    - test
#  image: ciricihq/gitlab-sonar-scanner:latest
#  variables:
#    SONAR_URL: http://zha-mvp-023-w10:9090
#    SONAR_ANALYSIS_MODE: preview
#  script:
#    - gitlab-sonar-scanner
#      -Dsonar.gitlab.project_id=$CI_PROJECT_ID
#      -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA
#      -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME
#  except:
##    - master@bcms/web/bcms_web_workbench
#    - kelvin
#  tags:
#    - SONAR_PREVIEW
#
#sonar_analyze:
#  stage: analysis
#  dependencies:
#    - test
#  image: ciricihq/gitlab-sonar-scanner:latest
#  variables:
#    GIT_STRATEGY: clone
#    GIT_DEPTH: "0"
#    SONAR_URL: http://zha-mvp-023-w10:9090
#    SONAR_ANALYSIS_MODE: publish
#  script:
#    - gitlab-sonar-scanner
#  only:
#    - kelvin
#  tags:
#    - SONAR_PREVIEW

build:
  stage: build
  cache:
    key: mynews_demo_node_modules
    policy: pull
    paths:
      - app/node_modules
  script:
    - cd app
    - npm run build:mp-weixin
    - npm run build:custom mp-dingtalk
  only:
    - kelvin
  tags:
    - MY_NEW
  artifacts:
    paths:
      - app/dist/build/mp-weixin
      - app/dist/build/mp-alipay
    expire_in: 3 days

deploy:
  stage: deploy
  cache:
    key: mynews_demo_node_modules
    policy: pull
    paths:
      - node_modules
  script:
    - node tools/upload.wx.js
  only:
    - kelvin
  tags:
    - MY_NEW
