stages:
  - build
  - deploy

build:
  stage: build
  only:
    - master
  before_script:
    - whoami
  script:
    - echo "build job"
  tags:
    - WP_WEIXIN

deploy:
  stage: deploy
  only:
    - master
  tags: 
    - WP_WEIXIN
  before_script:
    - whoami
  script:
    - echo "deploy job"
