variables:
  WEIXIN_DEPLOY_PATH: D:\deploy\weixin\mynews\
  DINGDING_DEPLOY_PATH: D:\deploy\dingding\mynews\

stages:
  - prepare
  - test
#  - analysis
  - build
  - deploy

prepare:
  stage: prepare
  cache:
    key: mynews_demo_node_modules
    paths:
      - node_modules
      - app/node_modules
  script:
    - pwd
    - npm install --registry https://registry.npm.taobao.org
    - cd app
    - setx PUPPETEER_SKIP_DOWNLOAD true
    - npm install
  only:
    - kelvin
  tags:
    - MY_NEW

test:
  stage: test
  cache:
    key: mynews_demo_node_modules
    policy: pull
    paths:
      - app/node_modules
  script:
    - pwd
    - cd app
    - npm run test
  only:
    - master
    - kelvin
  tags:
    - MY_NEW

#analysis:
#  stage: analysis
#  script:
#    - pwd
#    - cd app
#    - sonar-scanner
#  only:
#    - master
#    - kelvin
#  tags:
#    - MY_NEW

build:
  stage: build
  cache:
    key: mynews_demo_node_modules
    policy: pull
    paths:
      - app/node_modules
  script:
    - cd app
    - npm run build:mp-weixin
    - npm run build:custom mp-dingtalk
  only:
    - kelvin
  tags:
    - MY_NEW
  artifacts:
    paths:
      - app/dist/build/mp-weixin
      - app/dist/build/mp-alipay
    expire_in: 3 days

deploy:
  stage: deploy
  cache:
    key: mynews_demo_node_modules
    policy: pull
    paths:
      - node_modules
  script:
    - node tools/upload.wx.js
  only:
    - kelvin
  tags:
    - MY_NEW
